name: Format PR
on:
  pull_request:
    branches: [ main ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Apply Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier format .
